services:
  # ====================
  # Frontend
  # ====================
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev

  # ====================
  # Base de datos
  # ====================
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DATABASE:?error}
    ports:
      - "${DB_PORT:?error}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../dump_app_picadosYa.sql:/docker-entrypoint-initdb.d/init.sql
    

volumes:
  mysql_data:
