services:
  # ====================
  # Frontend
  # ====================
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev

  # ====================
  # Base de datos
  # ====================
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: app_picadosYa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../dump_app_picadosYa.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  mysql_data:
