basePath: /api
definitions:
  api.responseError:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  api.responseMessage:
    properties:
      message:
        type: string
    type: object
  models.Reservation:
    properties:
      date:
        type: string
      end_time:
        items:
          type: integer
        type: array
      field_id:
        type: integer
      id:
        type: integer
      reservation_date:
        type: string
      start_time:
        items:
          type: integer
        type: array
      status:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  title: PicadosYa API
  version: "1.0"
paths:
  /reservations:
    get:
      consumes:
      - application/json
      description: Devuelve una lista paginada de reservas
      parameters:
      - description: Número de reservas a obtener
        in: query
        name: limit
        type: integer
      - description: Desplazamiento para paginación
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Reservation'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseError'
      summary: Obtiene una lista de reservas
      tags:
      - reservations
    post:
      consumes:
      - application/json
      description: Crea una nueva reserva en el sistema
      parameters:
      - description: Reserva a crear
        in: body
        name: reservation
        required: true
        schema:
          $ref: '#/definitions/models.Reservation'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Reservation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.responseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseError'
      summary: Crea una reserva
      tags:
      - reservations
    put:
      consumes:
      - application/json
      description: Actualiza una reserva existente
      parameters:
      - description: Reserva a actualizar
        in: body
        name: reservation
        required: true
        schema:
          $ref: '#/definitions/models.Reservation'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reservation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.responseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseError'
      summary: Actualiza una reserva
      tags:
      - reservations
  /reservations/{id}:
    delete:
      consumes:
      - application/json
      description: Elimina una reserva específica por ID
      parameters:
      - description: ID de la reserva
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.responseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseError'
      summary: Elimina una reserva
      tags:
      - reservations
    get:
      consumes:
      - application/json
      description: Devuelve una reserva específica por ID
      parameters:
      - description: ID de la reserva
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reservation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.responseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseError'
      summary: Obtiene una reserva
      tags:
      - reservations
swagger: "2.0"
